### ISSUE TITLE
No save?

### ISSUE THREAD

**Issue by mgold** [enjalot/blockbuilder#117] opened 2016-02-02 03:39 UTC
I could have sworn there was a save feature at some point, but when I log in all I get is:

![screen shot 2016-02-01 at 10 38 19 pm](https://cloud.githubusercontent.com/assets/1191970/12739126/9917c0cc-c934-11e5-8863-73310540db23.png)

The only way to "save" is to fork, to a new gist, rather than upload a revision. What's going on?

**Comment by enjalot** [comment] 2016-02-02 03:40
yes, this is a bug with old sessions I believe. Can you try logging out and logging back in?
I'll need to get to the bottom of this as its been reported several times.

**Comment by mgold** [comment] 2016-02-02 03:50
Yup, that did it. But I don't think it was ever there to begin with in my old session?

**Comment by mgold** [comment] 2016-02-02 03:50
Also, you can close the issue if you like, however you want to manage tickets.

**Comment by enjalot** [comment] 2016-02-02 05:02
I think the problem is because i updated the module that manages user auth
(passport) and the way it handles sessions is slightly different. thats why
clearing the session by logging out seems to fix it.
Ill try to dig a little then close this.

**Comment by zeffii** [comment] 2016-02-02 14:41
what a coincidence, I had just found a good reason to use d3+blockbuilder and found myself forking indefinitely .. come here to see it's an issue. logged out, logged in. now the Save option has re-appeared. sweet.

**Comment by enjalot** [comment] 2016-02-06 00:13
alright, i fixed the root cause of this, and updated the broken data. It was a problem with updating passport and a mixup between numeric vs. string ids in the database. Nothing was lost except for the temporary disappearance of the save button!

**Closed by enjalot** 2016-02-06 00:13 UTC

**Comment by mgold** [comment] 2016-02-06 01:35
Wahoo!
