### ISSUE TITLE
something useful at blockbuilder.org/githubusername

### ISSUE THREAD

**Issue by steltenpower** [enjalot/blockbuilder#116] opened 2016-02-01 22:07 UTC
I'm probably not the only one sending my browser to blockbuilder.org/githubusername now and then.

Maybe there have

Meant bl.ocks.org/githubusername ?
Or blockbuilder.org 's main page?

**Comment by enjalot** [comment] 2016-02-04 01:18
yes, this is definitely high on the list and related to being able to create galleries.
I'd love to see people curate their own portfolios, as well as be able to see a gallery of their own private gists.

**Comment by Fil** [comment] 2016-06-21 05:11
see #95

**Comment by Fil** [comment] 2016-08-17 10:14
The page almost exists at http://blockbuilder.org/search#user=Fil

(makes me think blobkbuilder probably shouldn't list `[UNLISTED]` blocks in search)

**Comment by micahstubbs** [comment] 2017-05-11 20:07
will close as a duplicate of #95

**Closed by micahstubbs** 2017-05-11 20:07 UTC
Labels: duplicate, enhancement
