### ISSUE TITLE
Save Button

### ISSUE THREAD

**Issue by judehuang** [enjalot/blockbuilder#131] opened 2016-03-22 13:38 UTC
* Save button is not show on the latest Mac Chrome.
* On Mac Firefox, after a block is saved as private, the private lock is being displayed in the wrong place.

**Comment by georules** [comment] 2016-03-22 19:24
I cannot confirm this.  I see the save button both logged in and logged out OSX 10.11.3 Chrome 49.0.2623.8.

In firefox 44, my lock looks like this: 
![screen shot 2016-03-22 at 3 23 45 pm](https://cloud.githubusercontent.com/assets/775628/13964847/27818580-f042-11e5-9a09-554a0ab8251f.png)

Do you have any details that you think might help to reproduce these problems?

**Comment by judehuang** [comment] 2016-03-23 13:48
This is my Firefox
<img width="1119" alt="firefox-45 0 1" src="https://cloud.githubusercontent.com/assets/805485/13987088/4c64172e-f0dc-11e5-982b-176422bc6154.png">

And this is my Chrome
<img width="881" alt="chrome- 49 0 2623 87" src="https://cloud.githubusercontent.com/assets/805485/13987097/5b821a58-f0dc-11e5-8476-33e8b9298530.png">

**Comment by judehuang** [comment] 2016-03-23 13:52
Closed by mistake.

**Comment by enjalot** [comment] 2016-03-23 15:23
maybe its session weirdness again, can you try logging out in chrome and
logging back in?

**Comment by judehuang** [comment] 2016-03-23 16:42
Just tried that, logout/login. Still happens. Is there some kind of conditional code for save? I am attaching the Chrome to show there is no code for Save.
<img width="1101" alt="fork-no-save" src="https://cloud.githubusercontent.com/assets/805485/13992967/95afe1b6-f0f4-11e5-94b7-5366e5a569b1.png">

**Comment by georules** [comment] 2016-03-23 16:49
You cannot save anonymous blocks, you can only fork them.

**Comment by judehuang** [comment] 2016-03-23 17:51
Finally got it working. Now the lock is at the same position as FF.
<img width="1216" alt="save is working-chrome" src="https://cloud.githubusercontent.com/assets/805485/13995132/4435cf58-f0fe-11e5-8e39-cbecb5be8b59.png">

Thanks!

**Comment by enjalot** [comment] 2016-03-23 17:52
this looks like a styling bug due to a longer username. it's still
troubling that you had the save button issue. did it go away after
logout/login?

On Wed, Mar 23, 2016 at 10:51 AM, judehuang <notifications@github.com>
wrote:

> Finally got it working. Now the lock is at the same position as FF.
> [image: save is working-chrome]
> <https://cloud.githubusercontent.com/assets/805485/13995132/4435cf58-f0fe-11e5-8e39-cbecb5be8b59.png>
>
> Thanks!
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/enjalot/blockbuilder/issues/131#issuecomment-200464741>
>



-- 
Ian Johnson - 周彦
http://enja.org

**Comment by judehuang** [comment] 2016-03-23 18:02
maybe only related first time user creation (not a true login)?

**Comment by enjalot** [comment] 2016-07-12 22:48
fixed this, duplicate of #151

**Closed by enjalot** 2016-07-12 22:48 UTC
