### ISSUE TITLE
Matching bracket border hides cursor

### ISSUE THREAD

**Issue by mootari** [enjalot/blockbuilder#176] opened 2016-09-22 21:04 UTC
On Chrome, OS X, a cursor placed beside a highlighted matching bracket is barely visible. On a retina display it's even worse than it appears in the licecap-captured Gif below.

![cursor-hidden](https://cloud.githubusercontent.com/assets/322014/18766053/aefabb28-8118-11e6-92b0-e14352570d2a.gif)

I'd suggest using a value like `rgba(0,0,0,.2)` for matched bracket borders instead.

**Comment by micahstubbs** [comment] 2017-05-11 18:15
looks like functionality comes from the codemirror addon `matchbrackets`

http://codemirror.net/doc/manual.html#addon_matchbrackets

**Comment by micahstubbs** [comment] 2017-05-11 18:16
[source code](http://codemirror.net/addon/edit/matchbrackets.js) for the **codemirror** addon `matchbrackets`

**Comment by micahstubbs** [comment] 2017-05-11 18:18
looks like we can select the class `CodeMirror-matchingbracket` and style elements with that class

![screen shot 2017-05-11 at 11 17 31 am](https://cloud.githubusercontent.com/assets/2119400/25964999/88ac6c18-363b-11e7-9d77-897d2b566430.png)

**Comment by micahstubbs** [comment] 2017-05-11 18:24
ok, so `d3.selectAll('.CodeMirror-matchingbracket').style('opacity', 0.2);` seems to have the desired effect
![style-matching-bracket](https://cloud.githubusercontent.com/assets/2119400/25965310/6c96bd02-363c-11e7-82fd-299d1e350b1d.png)

**Comment by micahstubbs** [comment] 2017-05-11 18:35
add this style to [public/css/main.scss](public/css/main.scss) does the trick 🎉 

```
.CodeMirror-matchingbracket {
  opacity: 0.4;
}
```

I think `0.4` opacity is a bit better that `0.2`, where bracket is almost invisible on my monitor. 

a next-level thing (that's probably out of scope) would be to make this user configurable or even somehow detect the monitor type and optimize for that.

**Comment by micahstubbs** [comment] 2017-05-11 18:41
et voila

![better-matching-bracket-0 4](https://cloud.githubusercontent.com/assets/2119400/25966060/a58ea5be-363e-11e7-8191-1343e6ed6c32.gif)

**Comment by mootari** [comment] 2017-05-11 19:35
I think reducing the opacity for the whole bracket is not a good idea. Instead you'll want to either target the outline, or ideally raise the background:
```
.CodeMirror-matchingbracket {
    outline: none;
    background-color: #eeeeee;
}
```

**Comment by micahstubbs** [comment] 2017-05-11 19:46
looks like `outline: none` doesn't have the desired effect

**Comment by mootari** [comment] 2017-05-11 19:54
Not on its own. Here are some examples, the first being the one I recommended above. Screenshots taken in Chrome 58 on Mac.

```
.CodeMirror-matchingbracket {
  outline: none;
  background-color: #eeeeee;
}
```
![image](https://cloud.githubusercontent.com/assets/322014/25969038/cb6c3152-3693-11e7-8de0-ffe9bb3e7bc3.png)

```
.CodeMirror-matchingbracket {
  outline: lightgrey solid 1px;
}
```
![image](https://cloud.githubusercontent.com/assets/322014/25969047/d5a2714a-3693-11e7-882f-a770b7df1e16.png)

**Comment by micahstubbs** [comment] 2017-05-11 19:56
agree, that first screenshot does look nice.  will see if I can reproduce it.  also Chrome 58 on a Mac 😄

**Comment by micahstubbs** [comment] 2017-05-11 20:02
strange.  I see this:

```
.CodeMirror-matchingbracket {
  outline: none;
  background-color: #eeeeee;
}
```
![screen shot 2017-05-11 at 1 00 29 pm](https://cloud.githubusercontent.com/assets/2119400/25969487/e228597e-3649-11e7-9556-863f7804d312.png)

**Comment by mootari** [comment] 2017-05-11 20:08
Don't add the rules as-is, as they'll be overridden by the actual selector used on blockbuilder:
```
div.cm-s-mdn-like span.CodeMirror-matchingbracket {
    outline: grey solid 1px;
    color: inherit;
}
```
I'd recommend to place the cursor beside a bracket and then simply inspect the bracket.

**Comment by micahstubbs** [comment] 2017-05-11 20:14
@mootari not sure I follow.  can you make a branch on your fork of blockbuilder with this change?
 would help to look at that 😄

**Comment by mootari** [comment] 2017-05-11 21:44
The selector `div.cm-s-mdn-like span.CodeMirror-matchingbracket` (as seen on blockbuilder.org) has a higher specificity than the selector `.CodeMirror-matchingbracket`. Your `outline: none` declaration gets overridden by the declaration in the original CodeMirror theme. That's why your background color gets applied, but the outline is still present.

**Closed** 2017-05-11 23:43 UTC
Labels: bug, fixed
